## Pandas I/O: trabalhando com diferentes formatos de arquivos
`https://cursos.alura.com.br/course/pandas-io-trabalhando-diferentes-formatos-arquivos`

In [1]:
!python --version

Python 3.10.12

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [3]:
!pip show pandas

Name: pandas
Version: 1.5.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: The Pandas Development Team
Author-email: pandas-dev@python.org
License: BSD-3-Clause
Location: /usr/local/lib/python3.10/dist-packages
Requires: numpy, python-dateutil, pytz
Required-by: altair, arviz, bigframes, bokeh, bqplot, cmdstanpy, cufflinks, datascience, db-dtypes, dopamine-rl, fastai, geemap, geopandas, google-colab, gspread-dataframe, holoviews, ibis-framework, lida, mizani, mlxtend, pandas-datareader, pandas-gbq, panel, pins, plotnine, prophet, pymc, seaborn, sklearn-pandas, statsmodels, vega-datasets, xarray, yfinance

#### Fazendo leitura de arquivos CSV

In [4]:
import pandas as pd

In [5]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data.csv'

In [6]:
dados_mercado = pd.read_csv(url)
dados_mercado

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10142,1976,PhD,Divorced,66476.0,0,1,7/3/2013,99,372,...,47,48,78,2,5,2,11,4,0,0
2236,5263,1977,2n Cycle,Married,31056.0,1,0,1/22/2013,99,5,...,3,8,16,1,1,0,3,8,0,0
2237,22,1976,Graduation,Divorced,46310.0,1,0,3/12/2012,99,185,...,15,5,14,2,6,1,5,8,0,0
2238,528,1978,Graduation,Married,65819.0,0,0,11/29/2012,99,267,...,149,165,63,1,5,4,10,3,0,0
2239,4070,1969,PhD,Married,94871.0,0,2,1/9/2012,99,169,...,188,0,144,1,8,5,4,7,1,0

In [7]:
type(dados_mercado)

pandas.core.frame.DataFrame

In [8]:
dados_ponto_vírgula = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data_ponto_virgula.csv', sep=';')
dados_ponto_vírgula

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10142,1976,PhD,Divorced,66476.0,0,1,7/3/2013,99,372,...,47,48,78,2,5,2,11,4,0,0
2236,5263,1977,2n Cycle,Married,31056.0,1,0,1/22/2013,99,5,...,3,8,16,1,1,0,3,8,0,0
2237,22,1976,Graduation,Divorced,46310.0,1,0,3/12/2012,99,185,...,15,5,14,2,6,1,5,8,0,0
2238,528,1978,Graduation,Married,65819.0,0,0,11/29/2012,99,267,...,149,165,63,1,5,4,10,3,0,0
2239,4070,1969,PhD,Married,94871.0,0,2,1/9/2012,99,169,...,188,0,144,1,8,5,4,7,1,0

In [9]:
pd.read_csv(url, nrows=10)

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
5,7348,1958,PhD,Single,71691,0,0,3/17/2014,0,336,...,240,32,43,1,4,7,5,2,1,0
6,4073,1954,2n Cycle,Married,63564,0,0,1/29/2014,0,769,...,15,34,65,1,10,10,7,6,1,0
7,1991,1967,Graduation,Together,44931,0,1,1/18/2014,0,78,...,0,0,7,1,2,1,3,5,0,0
8,4047,1954,PhD,Married,65324,0,1,11/1/2014,0,384,...,21,32,5,3,6,2,9,4,0,0
9,9477,1954,PhD,Married,65324,0,1,11/1/2014,0,384,...,21,32,5,3,6,2,9,4,0,0

In [10]:
pd.read_csv(url, usecols=['Id', 'Year_Birth', 'Income'])

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [11]:
pd.read_csv(url, usecols=[0, 1, 4])

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [12]:
dados_mercado

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10142,1976,PhD,Divorced,66476.0,0,1,7/3/2013,99,372,...,47,48,78,2,5,2,11,4,0,0
2236,5263,1977,2n Cycle,Married,31056.0,1,0,1/22/2013,99,5,...,3,8,16,1,1,0,3,8,0,0
2237,22,1976,Graduation,Divorced,46310.0,1,0,3/12/2012,99,185,...,15,5,14,2,6,1,5,8,0,0
2238,528,1978,Graduation,Married,65819.0,0,0,11/29/2012,99,267,...,149,165,63,1,5,4,10,3,0,0
2239,4070,1969,PhD,Married,94871.0,0,2,1/9/2012,99,169,...,188,0,144,1,8,5,4,7,1,0

In [13]:
dados_mercado.to_csv('dados_mercado.csv', index=False)
!ls

dados_mercado.csv  sample_data

In [14]:
pd.read_csv('dados_mercado.csv')

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10142,1976,PhD,Divorced,66476.0,0,1,7/3/2013,99,372,...,47,48,78,2,5,2,11,4,0,0
2236,5263,1977,2n Cycle,Married,31056.0,1,0,1/22/2013,99,5,...,3,8,16,1,1,0,3,8,0,0
2237,22,1976,Graduation,Divorced,46310.0,1,0,3/12/2012,99,185,...,15,5,14,2,6,1,5,8,0,0
2238,528,1978,Graduation,Married,65819.0,0,0,11/29/2012,99,267,...,149,165,63,1,5,4,10,3,0,0
2239,4070,1969,PhD,Married,94871.0,0,2,1/9/2012,99,169,...,188,0,144,1,8,5,4,7,1,0

In [15]:
url_dados_sus = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/dados_sus.csv'

In [16]:
pd.read_csv(url_dados_sus,
            sep=';',
            encoding='ISO-8859-1',
            skiprows=3,
            skipfooter=9,
            engine='python')

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"
5,Amapá,"1120973,34","1268740,33","974651,24","1141137,32","866346,18","1440978,95","1426659,48","1475551,38","1651341,43",...,"3253399,45","2946398,44","2416019,23","2203732,04","2218532,26","2566919,60","2802886,34","2817849,31","3188210,98","309860092,59"
6,Tocantins,"3441592,69","4985688,85","6205612,60","4984482,09","5511002,46","4927934,22","5445602,28","5413710,38","5596669,50",...,"9155572,36","8390267,72","8729632,49","7770885,66","527840,46","675277,05","419553,49","319160,87","1357751,33","1020028272,64"
7,Maranhão,"10723506,39","13559679,41","13985142,36","14809416,46","14505727,38","14908091,32","15784899,40","15195312,89","14951277,75",...,"35473489,49","32219037,29","30077152,72","33200778,47","31942670,33","30783403,58","30738750,31","30924484,99","39663677,48","3871069498,04"
8,Piauí,"7985142,43","10079928,25","10298372,45","10775976,33","10398360,88","10528253,88","11040107,92","10549176,40","10899198,97",...,"19908573,27","25663537,49","20230782,72","22389215,72","18911604,50","20883972,79","22689390,32","19400269,01","20018325,75","2280888802,74"
9,Ceará,"15539821,90","25735101,55","28724625,75","30676457,06","30604453,47","31272395,18","30925391,36","27851438,72","30362719,90",...,"56019506,33","61719491,69","56625919,77","59074596,33","56916499,66","50849353,22","52078218,88","53171253,41","62079618,54","6591836650,18"
10,Rio Grande do Norte,"5947814,08","9509755,83","10352238,59","10855108,50","11160168,19","10475071,38","11386349,96","10640817,47","11336030,28",...,"26337808,77","27579658,62","27721340,38","26048003,33","24737052,09","23846816,35","28044464,51","26317613,74","23306498,68","2660122027,15"
11,Paraíba,"10723002,45","11386274,47","12053643,87","12653528,76","12215107,11","12256928,49","12755413,77","12872578,37","12558296,11",...,"27294311,05","23288213,79","19480481,07","19988426,94","18418075,59","18099514,43","19524543,63","21302722,77","25750897,89","2614919044,63"
12,Pernambuco,"14393949,89","24181400,95","29991302,71","34806197,97","32147987,35","32239094,89","32685640,76","35457038,66","33668261,46",...,"74914677,43","77232881,01","71715677,42","66555628,25","78904176,21","70978052,15","83846222,44","75562664,69","83870992,73","8581189975,91"
13,Alagoas,"6243726,32","8376622,16","8408336,22","9090794,82","9338771,45","10068210,08","9887061,61","9373432,00","9563580,50",...,"18453860,49","19995280,39","18185986,17","18871513,02","18597375,56","17805273,37","17543184,88","18526929,38","22118639,05","2236415402,51"
14,Sergipe,"2780750,11","3676483,16","5051473,61","5046063,36","4741151,56","5401259,63","5521904,44","5238398,50","5187912,19",...,"10313262,56","11404646,48","10741986,60","12278300,58","12264609,05","11454427,82","12060864,70","13003816,54","13321494,41","1215853015,00"
15,Bahia,"21211522,47","28189304,95","34181483,52","39026934,13","42949566,82","47025972,04","47481695,17","46931248,28","44883379,31",...,"84204991,86","83478081,57","80540324,01","81250834,02","86257814,00","85871122,17","79961693,17","81992571,15","98746333,07","9791541570,52"
16,Minas Gerais,"45671659,76","70194037,10","79231336,95","77136537,58","80554440,63","94758522,83","85360064,11","84722528,10","84601757,95",...,"165759955,94","171048093,95","175439696,53","178279152,74","175253226,91","172509435,62","174722161,98","177270694,34","200471045,07","20418737536,66"
17,Espírito Santo,"5456723,98","9102212,86","10249595,97","11253833,56","10198619,17","13364258,29","13035374,08","12588595,77","12727433,30",...,"33474963,98","32364742,01","38569356,14","35748380,19","32030401,25","33674687,78","39642483,39","40243896,20","45490499,45","3405850698,58"
18,Rio de Janeiro,"23025258,52","28394310,93","44567062,94","44054604,82","44911021,15","48056212,24","49872379,35","50912706,60","49270352,76",...,"99331352,01","96339615,99","88305239,94","86995649,35","86776500,97","90416725,95","94179674,42","85583557,95","106837295,81","10337391164,52"
19,São Paulo,"91678473,48","148677526,82","156087269,23","161227125,43","187119397,64","187291126,07","194398399,48","184854516,35","188636359,55",...,"367648996,72","349900969,68","354117254,42","345733068,79","335084865,66","330489045,98","355149525,60","348827130,99","392946147,42","41396604304,13"
20,Paraná,"38266347,46","55384670,52","53801318,85","52460306,69","54419620,71","57811688,48","58094241,83","56982774,90","57549082,26",...,"109720663,59","129529222,48","122702263,26","129647873,97","126859051,02","120037066,76","122122779,12","132622112,72","140264608,52","14681514706,67"
21,Santa Catarina,"16504913,45","25651429,11","26743524,89","27181488,26","26845308,18","29909762,04","30789135,84","31250854,33","30019676,93",...,"61267297,89","65467585,93","71781494,82","69414431,71","68460616,55","70333079,37","71970474,56","74337524,03","81376630,57","7835011163,40"
22,Rio Grande do Sul,"30931325,46","57363420,01","51547794,07","56673338,49","48397733,07","52413429,62","56636376,98","56113054,70","55356224,30",...,"100579287,65","102609965,59","104401019,54","117458292,46","108853890,98","111760506,80","119992419,94","111797400,70","130155185,16","12764391179,92"
23,Mato Grosso do Sul,"5377392,11","7002472,61","8423933,19","8797487,68","9770421,80","10905392,18","10249299,82","9671553,45","10218511,05",...,"18858844,44","19877080,68","19247894,51","19497210,85","22023126,25","19629591,55","21693311,15","24337295,63","25168195,34","2324525096,33"
24,Mato Grosso,"4795299,01","8684882,23","7886243,14","8794109,79","9231645,40","10221763,77","9163314,28","9243148,81","9052354,89",...,"16834650,98","19704915,36","20746227,60","22727405,20","20506039,58","19583803,46","19120141,68","18349376,92","19611032,61","2180119781,15"
25,Goiás,"15310637,29","22258668,68","21442515,75","20921212,45","21615970,67","18270043,87","20540517,13","20650730,67","20868443,56",...,"40606222,82","46229357,10","44889588,33","45529496,23","43037600,45","44147353,21","46127763,88","42742773,93","45592686,49","4973573613,47"
26,Distrito Federal,"4745919,19","7632480,67","9647203,26","11098732,99","12891719,72","12850125,67","12565646,74","13710857,89","13165106,20",...,"25269773,34","26526196,39","20056592,11","20856249,30","20459325,27","22991567,76","23527050,29","22766952,62","31831917,45","2592422853,56"
27,Total,"408424859,23","613174269,21","664043058,38","686662861,42","715803639,49","752181563,64","764990284,76","750608648,28","752962642,15",...,"1484010417,62","1514160823,72","1477904466,14","1489983146,21","1464196395,75","1441199605,05","1513991196,49","1500612299,36","1687562138,38","172481760138,88"

#### Utilizando planilhas

In [17]:
url = 'https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True'

In [18]:
dados_co2 = pd.read_excel(url)
dados_co2

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,3.609674e+10,1.450697e+10,1.224263e+10,7.144928e+09,1.507923e+09,391992176.0,302294047.0,4749682.0
63100,Global,WLD,2018,3.682651e+10,1.474683e+10,1.226602e+10,7.529847e+09,1.569218e+09,412115746.0,302478706.0,4792753.0
63101,Global,WLD,2019,3.708256e+10,1.472598e+10,1.234565e+10,7.647528e+09,1.617507e+09,439253991.0,306638573.0,4775633.0
63102,Global,WLD,2020,3.526409e+10,1.417456e+10,1.119181e+10,7.556290e+09,1.637538e+09,407583673.0,296301685.0,4497423.0
63103,Global,WLD,2021,3.712385e+10,1.497960e+10,1.183716e+10,7.921829e+09,1.672592e+09,416525563.0,296145746.0,4693699.0

In [19]:
pd.ExcelFile(url).sheet_names

['emissoes_C02', 'emissoes_percapita', 'fontes']

In [20]:
percapita = pd.read_excel(url, sheet_name='emissoes_percapita')
percapita

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,4749682.0,1908857.0,1610910.0,940144.0,198416.0,51579.0,39776.0
63100,Global,WLD,2018,4792753.0,1919213.0,1596350.0,979965.0,204225.0,53634.0,39366.0
63101,Global,WLD,2019,4775633.0,1896468.0,1589920.0,984878.0,208309.0,56569.0,39490.0
63102,Global,WLD,2020,4497423.0,1807760.0,1427353.0,963695.0,208844.0,51981.0,37789.0
63103,Global,WLD,2021,4693699.0,1893923.0,1496614.0,1001585.0,211472.0,52663.0,37443.0

In [21]:
todas_as_páginas = pd.read_excel(url, sheet_name=None)

In [22]:
todas_as_páginas['emissoes_C02']

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,3.609674e+10,1.450697e+10,1.224263e+10,7.144928e+09,1.507923e+09,391992176.0,302294047.0,4749682.0
63100,Global,WLD,2018,3.682651e+10,1.474683e+10,1.226602e+10,7.529847e+09,1.569218e+09,412115746.0,302478706.0,4792753.0
63101,Global,WLD,2019,3.708256e+10,1.472598e+10,1.234565e+10,7.647528e+09,1.617507e+09,439253991.0,306638573.0,4775633.0
63102,Global,WLD,2020,3.526409e+10,1.417456e+10,1.119181e+10,7.556290e+09,1.637538e+09,407583673.0,296301685.0,4497423.0
63103,Global,WLD,2021,3.712385e+10,1.497960e+10,1.183716e+10,7.921829e+09,1.672592e+09,416525563.0,296145746.0,4693699.0

In [23]:
todas_as_páginas['emissoes_percapita']

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,4749682.0,1908857.0,1610910.0,940144.0,198416.0,51579.0,39776.0
63100,Global,WLD,2018,4792753.0,1919213.0,1596350.0,979965.0,204225.0,53634.0,39366.0
63101,Global,WLD,2019,4775633.0,1896468.0,1589920.0,984878.0,208309.0,56569.0,39490.0
63102,Global,WLD,2020,4497423.0,1807760.0,1427353.0,963695.0,208844.0,51981.0,37789.0
63103,Global,WLD,2021,4693699.0,1893923.0,1496614.0,1001585.0,211472.0,52663.0,37443.0

In [24]:
todas_as_páginas['fontes']

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63100,Global,WLD,2018,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63101,Global,WLD,2019,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63102,Global,WLD,2020,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63103,Global,WLD,2021,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."

In [25]:
todas_as_páginas['fontes'].to_excel('fontes.xlsx', index=False)
!ls

dados_mercado.csv  fontes.xlsx	sample_data

In [26]:
pd.read_excel('fontes.xlsx')

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63100,Global,WLD,2018,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63101,Global,WLD,2019,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63102,Global,WLD,2020,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."
63103,Global,WLD,2021,"CDIAC 2022, BP, and Sum of countries",CDIAC 2022 and BP,CDIAC 2022 and BP,CDIAC 2022 and BP,Andrew cement,CDIAC 2022 and GCP,[NONE],"CDIAC 2022, BP, Sum of countries, and UN popul..."

In [27]:
sheet_id = '1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [28]:
pd.read_csv(url)

,Country,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),191.745.115,167.681.579,95.957.742,8.472.111,75.545.827,68.467.956,...,29.650.624,259.295.334,18.562.366,146.235.617,172.896.741,149.789.334,131.694.556,1.632.953,159.824.372,159.824.372
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),553.661.955,544.538.649,543.557.223,70.898.423,836.804.405,912.141.485,...,985.522.312,950.695.879,1.036.293.852,1.099.779.111,113.504.405,1.031.811.348,81.330.073,777.674.934,792.137.069,792.137.069
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819.541.634,124.281.022,683.699.826,638.307.036,645.355.189,605.436.253,...,166.942.319,150.324.046,1.533.630.039,1.668.337.371,160.377.515,1.557.664.358,1.788.786.074,1.782.738.948,169.224.832,169.224.832
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521.831.658,723.537.924,69.630.787,6.724.177.518,6.541.578.914,6.733.479.486,...,5.850.886.105,5.944.654.173,5.942.800.412,5.807.127.723,6.026.181.822,6.080.600.282,6.104.133.912,6.362.975.399,6.481.217.432,6.481.217.432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Samoa,WSM,East Asia & Pacific,CO2 emissions (metric tons per capita),55.283.574,609.756.098,604.266.119,658.221.486,592.806.881,705.674.802,...,1.066.843.067,1.057.703.002,1.048.701.723,1.092.498.145,1.240.245.954,1.542.099.372,1.586.830.344,1.478.626.161,1.522.124.134,1.522.124.134
211,"Yemen, Rep.",YEM,Middle East & North Africa,CO2 emissions (metric tons per capita),56.703.735,690.937.429,704.793.064,627.104.927,653.255.714,706.080.534,...,963.978.488,858.490.955,1.106.687.715,1.062.211.282,511.361.652,399.363.829,359.621.635,341.068.402,380.633.361,380.633.361
212,South Africa,ZAF,Sub-Saharan Africa,CO2 emissions (metric tons per capita),6.729.798.587,6.424.621.766,6.175.429.944,6.219.193.872,6.215.847.077,6.378.789.568,...,7.869.815.906,8.077.957.969,8.138.264.312,8.212.241.156,7.669.937.662,7.563.739.495,7.641.675.086,7.515.678.605,7.507.736.092,7.507.736.092
213,Zambia,ZMB,Sub-Saharan Africa,CO2 emissions (metric tons per capita),340.929.635,349.232.211,33.722.439,289.956.061,241.269.619,234.153.214,...,217.496.732,27.860.069,284.057.568,304.549.552,312.354.964,325.114.844,404.067.778,445.489.133,380.717.051,380.717.051
214,Zimbabwe,ZWE,Sub-Saharan Africa,CO2 emissions (metric tons per capita),1.585.443.976,1.713.321.439,1.694.415.977,1.539.740.958,1.417.186.242,135.661.892,...,88.488.553,915.734.944,919.824.123,889.104.126,899.769.991,78.544.084,726.297.071,857.411.269,80.297.852,80.297.852

#### Manipulando arquivos JSON

In [29]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/pacientes.json'

In [30]:
pacientes = pd.read_json(url)
pacientes

,ID_paciente,Doenca_cardiaca,IMC,Fumante,Consumo_alcool,AVC,Saude_fisica,Saude_mental,Dificuldade_caminhar,Sexo_biologico,Faixa_etaria,Raca,Diabetes,Atividade_fisica,Saude_geral,Horas_sono,Asma,Doenca_renal,Cancer_pele
0,0,Nao,16.60,Sim,Nao,Nao,3,30,Nao,Feminino,55-59,Branca,Sim,Sim,Muito boa,5,Sim,Nao,Sim
1,1,Nao,20.34,Nao,Nao,Sim,0,0,Nao,Feminino,80 ou +,Branca,Nao,Sim,Muito boa,7,Nao,Nao,Nao
2,2,Nao,26.58,Sim,Nao,Nao,20,30,Nao,Masculino,65-69,Branca,Sim,Sim,Razoavel,8,Sim,Nao,Nao
3,3,Nao,24.21,Nao,Nao,Nao,0,0,Nao,Feminino,75-79,Branca,Nao,No,Boa,6,Nao,Nao,Sim
4,4,Nao,23.71,Nao,Nao,Nao,28,0,Sim,Feminino,40-44,Branca,Nao,Sim,Muito boa,8,Nao,Nao,Nao
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Nao,28.29,Sim,Nao,Nao,10,20,Nao,Feminino,65-69,Preta,Sim,Sim,Razoavel,8,Nao,Nao,Nao
996,996,Nao,25.69,Sim,Nao,Nao,0,0,Nao,Feminino,75-79,Branca,Nao,Sim,Excelente,8,Nao,Nao,Nao
997,997,Sim,26.99,Nao,Nao,Nao,1,0,Nao,Masculino,70-74,Branca,Nao,Sim,Muito boa,8,Nao,Nao,Nao
998,998,Nao,44.29,Nao,Nao,Nao,30,0,Sim,Feminino,70-74,Branca,Sim,No,Boa,6,Sim,Nao,Nao
999,999,Nao,25.83,Nao,Nao,Nao,0,0,Nao,Masculino,70-74,Preta,Sim,No,Excelente,7,Nao,Nao,Nao

In [31]:
url_nested = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/pacientes_2.json'

In [32]:
pacientes_nested = pd.read_json(url_nested)
pacientes_nested

,Pesquisa,Ano,Pacientes
0,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_bi..."
1,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '02', 'Faixa_etaria': '80 ou +', 'Sexo_..."
2,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '03', 'Faixa_etaria': '65-69', 'Sexo_bi..."

In [33]:
pacientes_normalized = pd.json_normalize(pacientes_nested['Pacientes'])
pacientes_normalized

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,01,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,02,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,03,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"

In [34]:
pacientes_normalized.to_json('pacientes.json')
!ls

dados_mercado.csv  fontes.xlsx	pacientes.json	sample_data

In [35]:
pd.read_json('pacientes.json')

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,1,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,2,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,3,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"

In [36]:
import requests
import json

In [37]:
frutas = requests.get('https://fruityvice.com/api/fruit/all')

In [38]:
resultado = json.loads(frutas.text)

In [39]:
df_frutas = pd.DataFrame(resultado)
df_frutas

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."
10,Pineapple,10,Bromeliaceae,Poales,Ananas,"{'calories': 50, 'fat': 0.12, 'sugar': 9.85, '..."
11,Fig,68,Moraceae,Rosales,Ficus,"{'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c..."
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,"{'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca..."
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,"{'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c..."
14,Plum,71,Rosaceae,Rosales,Prunus,"{'calories': 46, 'fat': 0.28, 'sugar': 9.92, '..."
15,Orange,2,Rutaceae,Sapindales,Citrus,"{'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca..."
16,GreenApple,72,Rosaceae,Rosales,Malus,"{'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca..."
17,Raspberry,23,Rosaceae,Rosales,Rubus,"{'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca..."
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,"{'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca..."
19,Lemon,26,Rutaceae,Sapindales,Citrus,"{'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca..."
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,"{'calories': 60, 'fat': 0.38, 'sugar': 13.7, '..."
21,Blueberry,33,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
22,Apple,6,Rosaceae,Rosales,Malus,"{'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c..."
23,Guava,37,Myrtaceae,Myrtales,Psidium,"{'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca..."
24,Apricot,35,Rosaceae,Rosales,Prunus,"{'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca..."
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,"{'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca..."
26,Tangerine,77,Rutaceae,Sapindales,Citrus,"{'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca..."
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,"{'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca..."
28,Lime,44,Rutaceae,Sapindales,Citrus,"{'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca..."
29,Pomegranate,79,Lythraceae,Myrtales,Punica,"{'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c..."
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,"{'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca..."
31,Grape,81,Vitaceae,Vitales,Vitis,"{'calories': 69, 'fat': 0.16, 'sugar': 16.0, '..."
32,Morus,82,Moraceae,Rosales,Morus,"{'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c..."
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,"{'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca..."
34,Avocado,84,Lauraceae,Laurales,Persea,"{'calories': 160, 'fat': 14.66, 'sugar': 0.66,..."
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,"{'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca..."
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,"{'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca..."
37,Cherry,9,Rosaceae,Rosales,Prunus,"{'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca..."
38,Peach,86,Rosaceae,Rosales,Prunus,"{'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c..."
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,"{'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c..."
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,"{'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c..."
41,Hazelnut,96,Betulaceae,Fagales,Corylus,"{'calories': 628, 'fat': 61.0, 'sugar': 4.3, '..."
42,Pomelo,98,Rutaceae,Sapindales,Citrus,"{'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'ca..."
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,"{'calories': 73, 'fat': 0.58, 'sugar': 16.11, ..."
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,"{'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'ca..."
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,"{'calories': 70, 'fat': 0.2, 'sugar': 13.0, 'c..."
46,Papaya,42,Caricaceae,Brassicales,Carica,"{'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'ca..."
47,Annona,103,Annonaceae,Rosales,Annonas,"{'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'c..."
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,"{'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'ca..."

In [40]:
frutas_normalized = pd.json_normalize(resultado)
frutas_normalized

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20

#### Lendo dados em HTML e XML

In [41]:
import requests

url = "https://en.wikipedia.org/wiki/AFI's_100_Years...100_Movies"

response = requests.get(url)

if response.status_code == 200:
    with open('webpage.html', 'wb') as f:
        f.write(response.content)
    print("Webpage saved as webpage.html")
else:
    print("Failed to fetch the webpage")

Webpage saved as webpage.html

In [42]:
dados = pd.read_html('webpage.html')
dados

[                                                    0  \
 0                                                1998
 1                                                1999
 2                                                2000
 3                                                2001
 4                                                2002
 5                                                2003
 6                                                2004
 7                                                2005
 8                                                2005
 9                                                2006
 10                                               2006
 11                                               2007
 12                                               2008
 13  .mw-parser-output .hlist dl,.mw-parser-output ...

                                                     1
 0                                          100 Movies
 1                                           100 Stars
 2                                          100 Laughs
 3                                         100 Thrills
 4                                        100 Passions
 5                               100 Heroes & Villains
 6                                           100 Songs
 7                                    100 Movie Quotes
 8                                           25 Scores
 9                                          100 Cheers
 10                                        25 Musicals
 11                               100 Movies (Updated)
 12                                    AFI's 10 Top 10
 13  .mw-parser-output .hlist dl,.mw-parser-output ...  ,
                       Film  Release year              Director  \
 0             Citizen Kane          1941          Orson Welles
 1               Casablanca          1942        Michael Curtiz
 2            The Godfather          1972  Francis Ford Coppola
 3       Gone with the Wind          1939        Victor Fleming
 4       Lawrence of Arabia          1962            David Lean
 ..                     ...           ...                   ...
 118        Sophie's Choice          1982        Alan J. Pakula
 119  The Last Picture Show          1971     Peter Bogdanovich
 120     Do the Right Thing          1989             Spike Lee
 121           Blade Runner          1982          Ridley Scott
 122              Toy Story          1995         John Lasseter

                               Production companies 1998 Rank 2007 Rank
 0                               RKO Radio Pictures         1         1
 1                            Warner Bros. Pictures         2         3
 2           Paramount Pictures, Alfran Productions         3         2
 3                  Selznick International Pictures         4         6
 4                                 Horizon Pictures         5         7
 ..                                             ...       ...       ...
 118                              ITC Entertainment         -        91
 119                                BBS Productions         -        95
 120                  40 Acres and a Mule Filmworks         -        96
 121                The Ladd Company, Shaw Brothers         -        97
 122  Walt Disney Pictures, Pixar Animation Studios         -        99

 [123 rows x 6 columns]]

In [43]:
type(dados)

list

In [44]:
top = dados[1]
top

,Film,Release year,Director,Production companies,1998 Rank,2007 Rank
0,Citizen Kane,1941,Orson Welles,RKO Radio Pictures,1,1
1,Casablanca,1942,Michael Curtiz,Warner Bros. Pictures,2,3
2,The Godfather,1972,Francis Ford Coppola,"Paramount Pictures, Alfran Productions",3,2
3,Gone with the Wind,1939,Victor Fleming,Selznick International Pictures,4,6
4,Lawrence of Arabia,1962,David Lean,Horizon Pictures,5,7
...,...,...,...,...,...,...
118,Sophie's Choice,1982,Alan J. Pakula,ITC Entertainment,-,91
119,The Last Picture Show,1971,Peter Bogdanovich,BBS Productions,-,95
120,Do the Right Thing,1989,Spike Lee,40 Acres and a Mule Filmworks,-,96
121,Blade Runner,1982,Ridley Scott,"The Ladd Company, Shaw Brothers",-,97
122,Toy Story,1995,John Lasseter,"Walt Disney Pictures, Pixar Animation Studios",-,99

In [45]:
top.to_html('top.html')
!ls

dados_mercado.csv  fontes.xlsx	pacientes.json	sample_data  top.html  webpage.html

In [46]:
pd.read_html('top.html')

[     Unnamed: 0                   Film  Release year              Director  \
 0             0           Citizen Kane          1941          Orson Welles
 1             1             Casablanca          1942        Michael Curtiz
 2             2          The Godfather          1972  Francis Ford Coppola
 3             3     Gone with the Wind          1939        Victor Fleming
 4             4     Lawrence of Arabia          1962            David Lean
 ..          ...                    ...           ...                   ...
 118         118        Sophie's Choice          1982        Alan J. Pakula
 119         119  The Last Picture Show          1971     Peter Bogdanovich
 120         120     Do the Right Thing          1989             Spike Lee
 121         121           Blade Runner          1982          Ridley Scott
 122         122              Toy Story          1995         John Lasseter

                               Production companies 1998 Rank 2007 Rank
 0                               RKO Radio Pictures         1         1
 1                            Warner Bros. Pictures         2         3
 2           Paramount Pictures, Alfran Productions         3         2
 3                  Selznick International Pictures         4         6
 4                                 Horizon Pictures         5         7
 ..                                             ...       ...       ...
 118                              ITC Entertainment         -        91
 119                                BBS Productions         -        95
 120                  40 Acres and a Mule Filmworks         -        96
 121                The Ladd Company, Shaw Brothers         -        97
 122  Walt Disney Pictures, Pixar Animation Studios         -        99

 [123 rows x 7 columns]]

In [47]:
top.to_csv('top.csv', index=False)
!ls

dados_mercado.csv  fontes.xlsx	pacientes.json	sample_data  top.csv  top.html	webpage.html

In [48]:
pd.read_csv('top.csv')

,Film,Release year,Director,Production companies,1998 Rank,2007 Rank
0,Citizen Kane,1941,Orson Welles,RKO Radio Pictures,1,1
1,Casablanca,1942,Michael Curtiz,Warner Bros. Pictures,2,3
2,The Godfather,1972,Francis Ford Coppola,"Paramount Pictures, Alfran Productions",3,2
3,Gone with the Wind,1939,Victor Fleming,Selznick International Pictures,4,6
4,Lawrence of Arabia,1962,David Lean,Horizon Pictures,5,7
...,...,...,...,...,...,...
118,Sophie's Choice,1982,Alan J. Pakula,ITC Entertainment,-,91
119,The Last Picture Show,1971,Peter Bogdanovich,BBS Productions,-,95
120,Do the Right Thing,1989,Spike Lee,40 Acres and a Mule Filmworks,-,96
121,Blade Runner,1982,Ridley Scott,"The Ladd Company, Shaw Brothers",-,97
122,Toy Story,1995,John Lasseter,"Walt Disney Pictures, Pixar Animation Studios",-,99

In [49]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/imdb_top_1000.xml'

In [50]:
dados = pd.read_xml(url)
dados

,index,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,None
996,996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,None
997,997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,None,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,None
999,999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,None,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,None

In [51]:
dados.to_xml('imdb_rank.xml')
!ls

dados_mercado.csv  imdb_rank.xml   sample_data	top.html
fontes.xlsx	   pacientes.json  top.csv	webpage.html

In [52]:
pd.read_xml('imdb_rank.xml')

,level_0,index,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,0,0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,1,1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,2,2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,3,3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,4,4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,None
996,996,996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,None
997,997,997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,998,998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,None,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,None
999,999,999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,None,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,None

See you space cowboy...